version: '3.9'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: david0
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest
      PGDATA: /data/postgres
    networks:
      - dockerNet
  dev-cache:
    image: redis:4.0
    command: /bin/bash -c 'redis-server --appendonly yes'
    ports:
      - "6379:6379"
    mem_limit: 96m
    networks:
      - dockerNet
networks:
  dockerNet:
    driver: bridge
